//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int MusicID { get; set; }
        public string MusicTitle { get; set; }
        public string MusicFilePath { get; set; }
        public string MusicCategory { get; set; }
        public string MusicStatus { get; set; }
        public string MusicImage { get; set; }
        public string SingerName { get; set; }
        public string MusicLike { get; set; }
    }
}
