//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibraryManagmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowHistory
    {
        public int BorrowID { get; set; }
        public int BookID { get; set; }
        public string BorrowerName { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
    }
}
