//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskPriority { get; set; }
        public string TaskCategory { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string TaskDescription { get; set; }
        public string Status { get; set; }
    }
}
