//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddtoCart
    {
        public int CartID { get; set; }
        public string FoodName { get; set; }
        public string Description { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> DeliveryCharges { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> FoodQuantity { get; set; }
        public Nullable<int> TotalCharges { get; set; }
        public Nullable<int> UserID { get; set; }
        public int OrderQuantity { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
