//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMessage
    {
        public int Id { get; set; }
        public string SenderName { get; set; }
        public string EmailAddress { get; set; }
        public string SenderSubject { get; set; }
        public string SenderMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
