//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderName { get; set; }
        public Nullable<int> OrderPrice { get; set; }
        public Nullable<int> DeliveryCharges { get; set; }
        public string OrderImage { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmailAddress { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string Locality { get; set; }
        public string COD { get; set; }
        public string Place { get; set; }
        public string Packed { get; set; }
        public string Ontheway { get; set; }
        public string Delivered { get; set; }
        public Nullable<int> UserID { get; set; }
        public int OrderQuantity { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
